// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {projects} from '../models';

export function LoadProjects():Promise<Array<projects.MetaData>>;

export function OpenProject(arg1:string):Promise<void>;
